### ISSUE TITLE
video capture cable support

### ISSUE THREAD

**Issue by AstralHope** [sipper69/Control3#3]
Does this software only support MS2130 as video capture cable? I tried the laptop's built-in camera and the AVerMedia GC553 but couldn't get the picture. The keyboard and mouse simulation was successful.

**Comment by sipper69** [comment]
Should support any video source. 
Works with the built in cameras on my laptops as well. 
Did you try different encoding in the settings? 
I experienced no video on one of the laptops when the encoding was NV12.
Did not really dove into that, just used MJPEG.

**Comment by sipper69** [comment]
Community pointed out the issue (thnks Roberto).

It appears that sometimes the audio stream was used instead of the video stream!
See code update, I added stream criteria.

For the latest version with all updates (outside this repository), see the Microsoft App Store for a full, signed version.

Cheers

-----

            var vidStream = mediaCapture.FrameSources
                                        .FirstOrDefault(source => source.Value.Info.MediaStreamType == MediaStreamType.VideoPreview ||
                                                                  source.Value.Info.MediaStreamType == MediaStreamType.VideoRecord).Value;
