### ISSUE TITLE
Can't show window list after pressing Alt-tab and holding Alt key

### ISSUE THREAD

**Issue by skt041959** [sipper69/Control3#4]
After pressing Alt-Tab and holding the Alt key, the Windows system should continue displaying the list of windows. However, with Control3, it only switches to the most recent window.

By the way, will you continue updating the GitHub repository? When I attempt to build this repository to apply some fixes myself, I notice there are many differences compared to the store version.

**Comment by sipper69** [comment]
Hi skt041959,

Good catch!  Thank you. 

The CH9329 library used will send a "key release" of **everything** after every keypress, by simply sending 0x00.

But indeed. When you keep holding a modifier key (Alt in this case), the "key release" should send 0x00, but the first byte should still represent the active modifier keys.

I assume that will work, I will review, test and optimize the CH9329 library when I'll find the time.

No I do not maintain this repository, I leave that to the community.
This repository is just for inspiration, but of course I will share a fix like this when I can.

The release in the Microsoft App Store is a separate private branch.

Cheers

**Comment by sipper69** [comment]
Hi skt041959,

Keeping the modifier keys active at key release is being supported by the CH9329 chip!

It was quite some rework, but I updated the production version in the Microsoft App Store. 
I do not have the time to update this preview here, but a short overview of the actions below:

- I optimized and cleansed the CH9329 library.
- I uncoupled the KeyDown and KeyUp calls, they are now called seperately at each related key event
- The "Decoration" variable is provided with both the KeyUp and KeyDown methods

I fixed in bug in this repository related to updating the Decoration variable. 

I attached the translated documentation about the CH9329 chip fyi.

Cheers!
[CH9329-CN.translated.PDF](https://github.com/user-attachments/files/15741885/CH9329-CN.translated.PDF)
